/* spell-checker: disable */
const test_puzzles = {
  1: {
    "5x5 - Easy  ": [["ABBCC"], ["AABDD"], ["AADDD"], ["EEEDD"], ["EEEDD"]],
    "6x6 - Medium": [["AAAAAB"], ["AABBBB"], ["AAAABC"], ["DDDACC"], ["DEECCC"], ["DFFFFC"]],
    "8x8 - Medium": [
      ["AAABCDDC"],
      ["EAABCCCC"],
      ["EAAAAACA"],
      ["EAAAAAAA"],
      ["EEEFFGAA"],
      ["EFFFFGHA"],
      ["FFFFGGHH"],
      ["FFGGGHHH"],
    ],
  },
  2: {
    "10x10 - Easy": [
      ["AAAAAAAABB"],
      ["AAAAAACABB"],
      ["DEEEACCCBB"],
      ["DDDDFGGCBB"],
      ["DDDFFFGGBB"],
      ["DDHFFFGGBB"],
      ["DDHHHGGGIB"],
      ["DDDDDDGGIB"],
      ["DJJJJJJJII"],
      ["JJJJJJJJJI"],
    ],
    "10x10 - Medium": [
      ["AAAABBCCCC"],
      ["ADAABBBCBB"],
      ["ADDBBBBBBB"],
      ["DDDDBEEEEB"],
      ["DDBBBBBBEB"],
      ["FFFFGGHHHH"],
      ["FIFFGGGHGG"],
      ["FIIGGGGGGG"],
      ["IIIIGJJJJG"],
      ["IIGGGGGGJG"],
    ],
    "10x10 - Hard": [
      ["AAABBBBBBB"],
      ["AAACCDDDDB"],
      ["EEECCFDDDB"],
      ["EECCCFDDDG"],
      ["EECCCFFGGG"],
      ["EECHCFFFGG"],
      ["IIHHCCCJJG"],
      ["IIHHHCCJJJ"],
      ["IIIHHHHJJJ"],
      ["IIIHHHHJJJ"],
    ],
    "10x10 - Hard 2": [
      ["AABBBBBCCC"],
      ["AAABCBCCCD"],
      ["AEEBCCCCCD"],
      ["AECCCFFCCD"],
      ["EEEEEFCCDD"],
      ["GEHEEFFCCC"],
      ["GEHHHFFCCI"],
      ["GEHJHFHCCI"],
      ["GGJJHHHIII"],
      ["GGJJJHHHHH"],
    ],
  },
};
/* spell-checker: enabled */
export default test_puzzles;
